### ISSUE TITLE
Pressing CAPS LOCK or CTRL cause prompts to crash

### ISSUE THREAD

**Issue by kotx** [tauri-apps/create-tauri-app#266]
```
PS C:\Users\toast\workspace> pnpm create tauri-app
.../Local/pnpm/store/v3/tmp/dlx-47960    |   +2 +
Packages are copied from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\toast\AppData\Local\pnpm\store\v3
  Virtual store is at:             ../AppData/Local/pnpm/store/v3/tmp/dlx-47960/node_modules/.pnpm
.../Local/pnpm/store/v3/tmp/dlx-47960    | Progress: resolved 10, reused 2, downloaded 0, added 2, done

? Project name (tauri-app) › thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotConnected, error: "Not a terminal" }', D:\a\create-tauri-app\create-tauri-app\packages\cli\src\lib.rs:71:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ERROR  Command failed with exit code 3221226505: C:\Users\toast\AppData\Local\pnpm\store\v3\tmp\dlx-47960\node_modules\.bin\create-tauri-app.CMD

pnpm: Command failed with exit code 3221226505: C:\Users\toast\AppData\Local\pnpm\store\v3\tmp\dlx-47960\node_modules\.bin\create-tauri-app.CMD
    at makeError (C:\Users\toast\scoop\persist\nodejs-lts\bin\node_modules\pnpm\dist\pnpm.cjs:22289:17)
    at handlePromise (C:\Users\toast\scoop\persist\nodejs-lts\bin\node_modules\pnpm\dist\pnpm.cjs:22860:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (C:\Users\toast\scoop\persist\nodejs-lts\bin\node_modules\pnpm\dist\pnpm.cjs:199043:7)
    at async C:\Users\toast\scoop\persist\nodejs-lts\bin\node_modules\pnpm\dist\pnpm.cjs:206407:21
    at async run (C:\Users\toast\scoop\persist\nodejs-lts\bin\node_modules\pnpm\dist\pnpm.cjs:206378:34)
    at async runPnpm (C:\Users\toast\scoop\persist\nodejs-lts\bin\node_modules\pnpm\dist\pnpm.cjs:206599:5)
    at async C:\Users\toast\scoop\persist\nodejs-lts\bin\node_modules\pnpm\dist\pnpm.cjs:206591:7
```

**Comment by kotx** [comment]
Upon further inspection this is an issue of [`dialoguer`](https://github.com/mitsuhiko/dialoguer) which is used for prompts. Relevant PR here https://github.com/mitsuhiko/dialoguer/pull/192

Should this issue be left open then?

**Comment by amrbashir** [comment]
Yeah, let's leave it open for a while.

**Comment by amrbashir** [comment]
this should be fixed for a while now, let me know if you still face this issue.
