### ISSUE TITLE
sveltekit-ts cannot boot dev

### ISSUE THREAD

**Issue by kholbekj** [tauri-apps/create-tauri-app#333]
Hey hey, I'm a bit new to this whole pipeline, so unsure where the issue is, but when I run it with yarn/svelte-kit-ts, I can run `yarn` fine, but `yarn tauri dev` produces a few errors:

```bash
➜  yarn tauri dev
     Running BeforeDevCommand (`yarn dev`)


  VITE v4.1.1  ready in 500 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
        Info Watching /Users/me/src/project/src-tauri for changes...
   Compiling project v0.0.0 (/Users/me/src/project/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 2.01s
Error: Not found: /.yarn/unplugged/@sveltejs-kit-virtual-a7f97a66b5/node_modules/@sveltejs/kit/src/runtime/client/start.js
    at resolve (/.yarn/unplugged/@sveltejs-kit-virtual-a7f97a66b5/node_modules/@sveltejs/kit/src/runtime/server/respond.js:396:13)
    at resolve (/.yarn/unplugged/@sveltejs-kit-virtual-a7f97a66b5/node_modules/@sveltejs/kit/src/runtime/server/respond.js:237:5)
    at #options.hooks.handle (/.yarn/unplugged/@sveltejs-kit-virtual-a7f97a66b5/node_modules/@sveltejs/kit/src/runtime/server/index.js:41:55)
    at Module.respond (/.yarn/unplugged/@sveltejs-kit-virtual-a7f97a66b5/node_modules/@sveltejs/kit/src/runtime/server/respond.js:234:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
The request url "/Users/me/src/project/.yarn/unplugged/@sveltejs-kit-virtual-a7f97a66b5/node_modules/@sveltejs/kit/src/runtime/client/start.js" is outside of Vite serving allow list.

- /Users/me/src/project/src/lib
- /Users/me/src/project/src/routes
- /Users/me/src/project/.svelte-kit
- /Users/me/src/project/src
- /Users/me/src/project/node_modules
- /Users/me/src/project/.yarn/__virtual__/vite-virtual-86c2dfa513/0/cache/vite-npm-4.1.1-99b7c0ca45-aad14b660b.zip/node_modules/vite/dist/client

Refer to docs https://vitejs.dev/config/server-options.html#server-fs-allow for configurations and more details.

Error: Not found: /.yarn/unplugged/@sveltejs-kit-virtual-a7f97a66b5/node_modules/@sveltejs/kit/src/runtime/client/start.js
    at resolve (/.yarn/unplugged/@sveltejs-kit-virtual-a7f97a66b5/node_modules/@sveltejs/kit/src/runtime/server/respond.js:396:13)
    at resolve (/.yarn/unplugged/@sveltejs-kit-virtual-a7f97a66b5/node_modules/@sveltejs/kit/src/runtime/server/respond.js:237:5)
    at #options.hooks.handle (/.yarn/unplugged/@sveltejs-kit-virtual-a7f97a66b5/node_modules/@sveltejs/kit/src/runtime/server/index.js:41:55)
    at Module.respond (/.yarn/unplugged/@sveltejs-kit-virtual-a7f97a66b5/node_modules/@sveltejs/kit/src/runtime/server/respond.js:234:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
The request url "/Users/me/src/project/.yarn/unplugged/@sveltejs-kit-virtual-a7f97a66b5/node_modules/@sveltejs/kit/src/runtime/client/start.js" is outside of Vite serving allow list.
```

**Comment by amrbashir** [comment]
does `yarn dev` work? if not, probably an issue with yarn@berry PnP feature

**Comment by kholbekj** [comment]
@amrbashir `yarn dev` (and then actually going to the url) produces the same error indeed. Does that mean I should report somewhere else?

**Comment by amrbashir** [comment]
See https://kit.svelte.dev/faq#does-it-work-with-yarn-2

**Comment by kholbekj** [comment]
Aha! Well, that's fair then! Thanks for the pointer!
