### ISSUE TITLE
Error: Stuck at package name section when creating new tauri app

### ISSUE THREAD

**Issue by LazyYuuki** [tauri-apps/create-tauri-app#339]
When I tried to use the bash to create a new tauri app, if I do not put anything in the Package name field, I got an invalid argument error as shown below:

```
sh <(curl https://create.tauri.app/sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16121  100 16121    0     0   221k      0 --:--:-- --:--:-- --:--:--  238k
info: downloading create-tauri-app

✔ Project name · .
✔ Package name · 
✔ Choose your package manager · pnpm
✔ Choose your UI template · solid-ts
error: Invalid argument (os error 22)
```

When I do put someting in the Package name field, I got an invalid argument error also:

```
sh <(curl https://create.tauri.app/sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16121  100 16121    0     0   265k      0 --:--:-- --:--:-- --:--:--  297k
info: downloading create-tauri-app

✔ Project name · .
✔ Package name · test
✔ Choose your package manager · pnpm
✔ Choose your UI template · solid-ts
error: Invalid argument (os error 22)
```

My question is what is the package name refer to that all of my entry resulted in invalid argument? For testing sake I also use the pnpm method, in which I receive a similar result.

```
pnpm create tauri-app . --template solid-ts --manager pnpm.../Library/pnpm/store/v3/tmp/dlx-31442  |   +2 +
Packages are copied from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/yuuki/Library/pnpm/store/v3
  Virtual store is at:             ../../../Library/pnpm/store/v3/tmp/dlx-31442/node_modules/.pnpm
.../Library/pnpm/store/v3/tmp/dlx-31442  | Progress: resolved 10, reused 2, downloaded 0, added 2, done

✔ Package name · 
error: Invalid argument (os error 22)
 ERROR  Command failed with exit code 1: create-tauri-app . --template solid-ts --manager pnpm

pnpm: Command failed with exit code 1: create-tauri-app . --template solid-ts --manager pnpm
    at makeError (/Users/yuuki/.cache/node/corepack/pnpm/7.27.1/dist/pnpm.cjs:23113:17)
    at handlePromise (/Users/yuuki/.cache/node/corepack/pnpm/7.27.1/dist/pnpm.cjs:23684:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (/Users/yuuki/.cache/node/corepack/pnpm/7.27.1/dist/pnpm.cjs:218866:7)
    at async /Users/yuuki/.cache/node/corepack/pnpm/7.27.1/dist/pnpm.cjs:226543:21
    at async main (/Users/yuuki/.cache/node/corepack/pnpm/7.27.1/dist/pnpm.cjs:226512:34)
    at async runPnpm (/Users/yuuki/.cache/node/corepack/pnpm/7.27.1/dist/pnpm.cjs:226742:5)
    at async /Users/yuuki/.cache/node/corepack/pnpm/7.27.1/dist/pnpm.cjs:226734:7
```

I am running on an Apple M1 Pro, MacOS Venture 13.1. Appreciate for the help.

**Comment by amrbashir** [comment]
For the package name issue, it is already fixed in `dev` branch, as for the `os error`, I opened #342 to fix this. thanks for the report.
