### ISSUE TITLE
[bug] create-tauri-app caused error via pnpm with vite

### ISSUE THREAD

**Issue by kiochan** [tauri-apps/create-tauri-app#4]
### Describe the bug

If use create-tauri-app package to create vue app via pnpm with create-vite, it will returns a error message insteads of create package use vite template.

### Reproduction

```
pnpm create tauri-app
```

and choose `create-vite (vanilla, vue, react, svelte, preact, lit) (https://vitejs.dev/guide
/#scaffolding-your-first-vite-project)`

then choose `vue-ts`

it will returns:
```
 ERROR   ERROR  Unknown option: 'template'
Did you mean 'test-pattern'? Use "--config.unknown=value" to force an unknown option.
For help, run: pnpm help create
Error with command: pnpm
Error: Error: Command failed with exit code 1: pnpm create vite tauri-app --template vue-ts
    at C:\Users\kiochan\AppData\Local\Temp\dlx-23528\5\node_modules\.pnpm\create-tauri-app@1.0.0-rc.2\node_modules\create-tauri-app\dist\index.js:62:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\kiochan\AppData\Local\Temp\dlx-23528\5\node_modules\.pnpm\create-tauri-app@1.0.0-rc.2\node_modules\create-tauri-app\dist\index.js:39:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected behavior

It should create package with command:
```
pnpm create vite tauri-app -- --template vue-ts
```
insteads of
```
pnpm create vite tauri-app --template vue-ts
```

### Platform and versions

```shell
Operating System - Windows, version 10.0.19044 X64
Webview2 - 98.0.1108.56
Visual Studio Build Tools - Not installed
WARNING: no lock files found, defaulting to npm

Node.js environment
  Node.js - 16.5.0
  @tauri-apps/cli - 1.0.0-rc.5
  @tauri-apps/api - Not installed

Global packages
  npm - 7.19.1
  pnpm - 6.31.0
  yarn - 1.22.10

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-gnu

App directory structure
/tauri-app

App
```

**Comment by kiochan** [comment]
Sorry, I just read the new version of create-vite's document.
We should run `pnpm dlx create-vite <app> --template <template>` insteads of `pnpm create vite -- --template <template>`

ref.: https://www.npmjs.com/package/create-vite/v/2.6.6

**Comment by kiochan** [comment]
This issue is till not fixed, am I doing it wrong?
Or this fix is just not published yet?

```
PS C:\Users\kiochan> pnpm dlx create-tauri-app
Packages: +99
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\kiochan\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 99, reused 86, downloaded 13, added 99, done

C:\Users\kiochan\AppData\Local\Temp\dlx-23028\5:
+ create-tauri-app 1.0.0-rc.2

We hope to help you create something special with Tauri!
You will have a choice of one of the UI frameworks supported by the greater web tech community.
This tool should get you quickly started. See our docs at https://tauri.studio/

If you haven't already, please take a moment to setup your system.
You may find the requirements here: https://tauri.studio/en/docs/get-started/setup-windows/

Press any key to continue...
? What is your app name? tauri-app
? What should the window title be? Tauri App
? What UI recipe would you like to add? create-vite (vanilla, vue, react, svelte, preact, lit) (https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
? Add "@tauri-apps/api" npm package? Yes
? Which vite template would you like to use? vue-ts
>> Running initial command(s)
 ERROR   ERROR  Unknown option: 'template'
Did you mean 'test-pattern'? Use "--config.unknown=value" to force an unknown option.
For help, run: pnpm help create
Error with command: pnpm
Error: Error: Command failed with exit code 1: pnpm create vite tauri-app --template vue-ts
    at C:\Users\kiochan\AppData\Local\Temp\dlx-23028\5\node_modules\.pnpm\create-tauri-app@1.0.0-rc.2\node_modules\create-tauri-app\dist\index.js:62:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\kiochan\AppData\Local\Temp\dlx-23028\5\node_modules\.pnpm\create-tauri-app@1.0.0-rc.2\node_modules\create-tauri-app\dist\index.js:39:65)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
PS C:\Users\kiochan>
```

**Comment by amrbashir** [comment]
it is not published yet.

**Comment by amrbashir** [comment]
it is published now.
