### ISSUE TITLE
Error Using Git Bash under Windows

### ISSUE THREAD

**Issue by JamesWiresmith** [tauri-apps/create-tauri-app#86]
Perhaps a bit of an odd combo but I hit an error when running under git bash on Windows:

```
TypeError: process.stdin.setRawMode is not a function
    at C:\Users\JamesMcNally\AppData\Local\npm-cache\_npx\b58944764482de26\node_modules\create-tauri-app\dist\index.js:667:19
    at Generator.next (<anonymous>)
    at C:\Users\JamesMcNally\AppData\Local\npm-cache\_npx\b58944764482de26\node_modules\create-tauri-app\dist\index.js:40:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\JamesMcNally\AppData\Local\npm-cache\_npx\b58944764482de26\node_modules\create-tauri-app\dist\index.js:36:12)
    at keypress (C:\Users\JamesMcNally\AppData\Local\npm-cache\_npx\b58944764482de26\node_modules\create-tauri-app\dist\index.js:664:28)
    at C:\Users\JamesMcNally\AppData\Local\npm-cache\_npx\b58944764482de26\node_modules\create-tauri-app\dist\index.js:692:11
    at Generator.next (<anonymous>)
    at C:\Users\JamesMcNally\AppData\Local\npm-cache\_npx\b58944764482de26\node_modules\create-tauri-app\dist\index.js:40:71
    at new Promise (<anonymous>)
```
I presume this relates to this line:
https://github.com/tauri-apps/create-tauri-app/blob/fe5d9caecf0988beda5f1f9bf371bb467fc4b717/src/index.ts#L127

When I run under the Windows command line it runs without the error.

Versions:

Git bash: 2.37.1
Node: 16.16.0

**Comment by amrbashir** [comment]
`process.stdin.setRawMode` is only available when the shell is a tty, and I think git bash is not considered one. Anyhow, with the upcoming rewrite in #77, this will be solved.
